frontend monitoring

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -92,11 +92,6 @@ jobs:
           cd terraform
           terraform apply -auto-approve
 
-      # - name: Apply Terraform (second run)
-      #   run: |
-      #     cd terraform
-      #     terraform apply -auto-approve
-
       - name: Output Terraform results
         run: |
           cd terraform
@@ -182,16 +177,16 @@ jobs:
       - name: Extract IPs from inventory and check services
         run: |
           cd ansible
-          db_public_ip=$(grep 'db ansible_host' inventory.ini | cut -d '=' -f2 | cut -d 'a' -f1 | tr -d ' ')
+          # db_public_ip=$(grep 'db ansible_host' inventory.ini | cut -d '=' -f2 | cut -d 'a' -f1 | tr -d ' ')
           pgadmin_public_ip=$(grep 'monitoring ansible_host' inventory.ini | cut -d '=' -f2 | cut -d 'a' -f1 | tr -d ' ')
           loadbalancer_public_ip=$(grep 'loadbalancer ansible_host' inventory.ini | cut -d '=' -f2 | cut -d 'a' -f1 | tr -d ' ')
           
-          # Check PostgreSQL port with TCP connection test
-          echo "Checking PostgreSQL connection..."
-          if ! timeout 10 bash -c "</dev/tcp/$db_public_ip/5432"; then
-            echo "Error: PostgreSQL at $db_public_ip:5432 is not reachable"
-            exit 1
-          fi
+          # # Check PostgreSQL port with TCP connection test
+          # echo "Checking PostgreSQL connection..."
+          # if ! timeout 10 bash -c "</dev/tcp/$db_public_ip/5432"; then    # DB not acessible public so removed
+          #   echo "Error: PostgreSQL at $db_public_ip:5432 is not reachable"
+          #   exit 1
+          # fi
           
           # Check HTTP services - more flexible matching for HTTP status codes
           http_urls=(
